KaleidoScope \
    --mode kmanager_distributed \
    --kman_parallel 8 \
    --max_concurrent_fault 5000 \
    --vfiles ./Inputs/s9234_scan.vfiles \
    --clkdef ./Inputs/s9234_scan.clks \
    --alarm ./Inputs/bist.alarms \
    --fault_list ./Inputs/bist.faults \
    --top s9234_scan \
    --error_inject_inst TOP.s9234_scan \
    --sim_vcd ./Inputs/s9234_scan_vcd_bist.f \
    --ini parser_messages=true \
    --ini dft=true
